#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source ${DIR}/../configs.sh

SERVER=${1}
SERVER_PORT=${2}
WARMUP=${3}
MAXREQ=${4}
QPS=${5}
THREADS=${6}
TBENCH_ID=${7}

AUDIO_SAMPLES=/home/${USER_NAME}/Tailbenchplusplus/sphinx/audio_samples

TBENCH_WARMUPREQS=${WARMUP} TBENCH_MAXREQS=${MAXREQ} TBENCH_ID=${TBENCH_ID} TBENCH_SERVER=${SERVER} \
  TBENCH_SERVER_PORT=${SERVER_PORT} TBENCH_CLIENT_THREADS=${THREADS} \
  TBENCH_QPS=${QPS} TBENCH_MINSLEEPNS=10000 TBENCH_AN4_CORPUS=${DATA_ROOT}/sphinx \
  TBENCH_AUDIO_SAMPLES=${AUDIO_SAMPLES} ./decoder_client_networked &
echo "[CLIENT] : STARTED"
wait $!
echo "[CLIENT] : FINISHED"
